---

- name: generate ssh key and push to each other
  hosts: nodes
  gather_facts: no
  tasks:
    - name: generate the ssh key
      shell: "echo -e 'y\n' | ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa"

    - name: save the old authorized keys file
      copy:
        src: "~/.ssh/authorized_keys"
        dest: "~/.ssh/authorized_keys.bak"
        remote_src: yes

    - name: fetch the ssh key
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "/tmp/id_rsa_{{ inventory_hostname }}.pub"
        flat: yes

    - name: copy the authorized key to nodes
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('pipe','cat /tmp/*.pub') }}"
