---

- name: generate ssh key and push to all docker  nodes
  hosts: mito_nodes
  gather_facts: no
  tasks:
    - block:
        - name: generate the ssh key
          shell: "ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa"

      rescue:
        - name: forcing the new ssh keygen
          shell: "echo -e 'y\n' | ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa"
    
    - name: save the old authorized keys file
      copy:
        src: "~/.ssh/authorized_keys"
        dest: "~/.ssh/authorized_keys.bak"
        remote_src: yes

    - name: fetch the ssh key
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "~/id_rsa_{{ inventory_hostname }}.pub"
        flat: yes

    - name: copy the authorized key to nodes
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('pipe','cat /root/*.pub') }}"

